# Generated by Django 3.1.1 on 2020-10-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_auto_20201007_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
