# Generated by Django 3.1.1 on 2020-10-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_profile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_pic.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
