# Generated by Django 3.1.1 on 2020-10-08 17:58

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_auto_20201008_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mini',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='profile_pic.jpg', upload_to=''),
        ),
    ]
