# Generated by Django 3.1.1 on 2020-10-08 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0005_profile_mini'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mini',
        ),
    ]
