# Generated by Django 3.1.1 on 2020-10-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0008_auto_20201008_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
