# Generated by Django 3.1.1 on 2020-10-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0010_remove_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
