# Generated by Django 3.1.1 on 2020-10-06 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('image', '0007_auto_20201005_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumb',
        ),
    ]
