# Generated by Django 3.1.1 on 2020-10-06 17:52

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):
    dependencies = [
        ('image', '0008_remove_image_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumb',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
