# Generated by Django 3.1.1 on 2020-10-06 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('image', '0009_image_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumb',
        ),
    ]
