# Generated by Django 3.1.1 on 2020-10-11 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('image', '0011_image_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='like',
        ),
    ]
