# Generated by Django 3.1.1 on 2020-10-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('image', '0012_remove_image_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
